export const ROUTES: string[] = [
  '/',
  '/lazy',
  '/404',
  '/login',
  '/register',
  '/profile',
  '/products',
  '/products/product/*',
  '/admin',
  '/admin/categories',
  '/admin/products',
  '/admin/addproduct',
  '/admin/editproduct*',
];
